### ISSUE TITLE
raa triangle too large

### ISSUE THREAD

**Issue by genedan** [genedan/cl-practitioners-guide#2]
The raa triangle has just 1 too many development periods to be neatly rendered in the PDF. This is okay for a first draft. We can decide what to do once we get more clarity on what the final output format of the paper will be. If the format (html?) is wide enough to accommodate our data, we should be okay. Otherwise we can choose a smaller triangle or maybe experiment with the font size for code.

**Comment by kennethshsu** [comment]
Won't fix!
