### ISSUE TITLE
Create Scholar One account - John Bogaardt

### ISSUE THREAD

**Issue by genedan** [genedan/cl-practitioners-guide#23]
Hey @jbogaardt, could you create a CAS Scholar One account and/or send the email you used to create the account? I have to do a coauthor lookup to add you and it's done via email search.

**Comment by jbogaardt** [comment]
This has been created using jbogaardt@gmail.com

**Comment by kennethshsu** [comment]
Do I have one?

**Comment by genedan** [comment]
I found both of you, so we should be good. Yours is under your gmail address, @kennethshsu .

**Comment by kennethshsu** [comment]
Ok awesome!
