### ISSUE TITLE
Scholar One keywords

### ISSUE THREAD

**Issue by genedan** [genedan/cl-practitioners-guide#25]
We can enter some keywords, I just pulled stuff off the top of my head and kind of struggled with them, so I'm open to other ideas if you guys want some particular words:

![image](https://github.com/genedan/cl-practitioners-guide/assets/6165650/861182be-3f4e-4bca-85aa-3db07bfc9732)

**Comment by kennethshsu** [comment]
Some suggestions:

- open source -> open-source tools
- workflow -> workflow management
- chainladder -> chainladder-python
- software -> reserving software
- reserving -> standardized reserving? Or stochastic reserving? 
- workflow -> workflow design
- collaboration (new)
- dependencies management (new)

Will try to think of some more or iron out the above ideas.
