### ISSUE TITLE
CAS Taxonomy

### ISSUE THREAD

**Issue by genedan** [genedan/cl-practitioners-guide#26]
We can select 3 categories for our paper, the full list of items is too large to paste here but you can get a similar list on the CAS research library page, so if you had thoughts on a proper category I can update what I entered.

https://www.casact.org/publications-research/library

![image](https://github.com/genedan/cl-practitioners-guide/assets/6165650/a7f3daee-0474-48c2-ad8a-63eb3cbb1235)

**Comment by kennethshsu** [comment]
What's the difference between these? Are they nested?
