### ISSUE TITLE
Copyrighted material

### ISSUE THREAD

**Issue by genedan** [genedan/cl-practitioners-guide#27]
I know we have some triangles that come from other sources, what are your thoughts on this?

![image](https://github.com/genedan/cl-practitioners-guide/assets/6165650/f4109225-30e9-4075-a303-8a3dfa620e14)

**Comment by kennethshsu** [comment]
I don't think the data is copyrighted is it? The only "data" that I used is the `raa` and `clrd`, both are heavily used in other CAS papers already.

I think we can answer no for this one.

**Comment by genedan** [comment]
Assigning @jbogaardt for citations.

**Comment by kennethshsu** [comment]
I think the `clrd` is from Loss Reserving Data Pulled from NAIC Schedule P by Glenn G. Meyers, PhD, FCAS and Peng Shi, PhD, ASA. [Link](https://www.casact.org/publications-research/research/research-resources/loss-reserving-data-pulled-naic-schedule-p). I couldn't find the exact dataset though.

`raa` is from [Which Stochastic Model is Underlying the Chain Ladder Method?](https://www.casact.org/sites/default/files/2021-02/1994-mack.pdf), Thomas Mack, PhD, 1994
