### ISSUE TITLE
Create author bios

### ISSUE THREAD

**Issue by genedan** [genedan/cl-practitioners-guide#29]

**Comment by kennethshsu** [comment]
Mr. John Bogaardt FCAS, MAAA, currently serves as Chief Actuary for WCF Insurance. WCF Insurance is the leading workers’ compensation carrier in the state of Utah. In addition to workers comp, WCF offers several commercial lines products in the western region. As an actuary, John has responsibilities over the pricing, reserving, and predictive modeling functions of the company. As Head of the Business Intelligence team, John uses his passion for data science to push data-driven thinking and decision making well beyond the technical roles like Actuarial. John is the initial author and a maintainer of the chainladder-python package.

Mr. Kenneth Hsu, FCAS, CSPA, MAAA, is the Head of Actuarial at Breach Insurance, an insurtech start-up focusing on building regulated insurance solutions for the crypto and web3 industry. Kenneth has experience developing new insurance products and had rendered reserves opinions for unique insurance risks. He obtained his Bachelor’s degree from University of California, Riverside, and his Master’s degree from Columbia University. Kenneth is an award-winning volunteer for the Casualty Actuarial Society, and is also a core contributor to the most popular open-source actuarial package: chainladder-python.

**Comment by genedan** [comment]
Gene Dan, FCAS, CSPA, MAAA, is an actuary at SCOR. His primary responsibilities involve the development of SCOR's internal systems to price both treaty reinsurance and single-risk business. Prior to SCOR, he specialized in predictive modeling in both pricing and claims at various commercial insurers. Gene is a contributor to several open-source actuarial packages, including chainladder-python. He is the primary maintainer of the TmVal and PCDM actuarial packages, and is the main developer of the open-source reserving system FASLR.
