### ISSUE TITLE
30-word paper description

### ISSUE THREAD

**Issue by genedan** [genedan/cl-practitioners-guide#30]

**Comment by kennethshsu** [comment]
Abstract: 

Practicing actuaries are managing more complex
system and workflows every day, especially in
reserving. While reserving in of itself is a complex
topic, many actuaries prefer routine workflows
that are intuitive and easy to manage.
This paper discusses practical considerations on
the analytical and workflow structure of setting
an unpaid claim estimate. Literature abounds on
actuarial methods and assumptions used to
tackle specific reserving issues, but there is very
little research into the best practices of managing
actuarial reserving workflows. Management
teams of companies increasingly desire
1. Faster speed in end-to-end analysis,
2. Lower cost in running a reserving shop, and
3. More detailed insight into the drivers of loss
experience
These pressures continue to shape the evolution
of reserving against a backdrop of technology
advancements that are outpacing advancements
in actuarial reserving processes.
To address these pressures, we propose a
standard for data management of the loss
triangle along with a standard for building
actuarial models with an explicit declaration of
model assumptions. This standard is manifested
in the open-source package called chainladder-
python, and we will demonstrate its use in core
reserving as well as its integration into actuarial
departments&#39; workflows from a practical
perspective.

**Comment by kennethshsu** [comment]
In this paper, the authors of popular open-source actuarial packages propose methods of how to manage reserving workflow and system architecture for an actuarial function.
